#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: bashstyle-ng
## @Creation date file: 06.10.2020, 21:12:01

[[ -z "${bashstyle_ng_script_source}" ]] && declare -rx bashstyle_ng_script_source="$BASH_SOURCE"

if [[ -z "${bashstyle_ng_script_source_path}" ]]; then
  temp_one="$(dirname ${bashstyle_ng_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx bashstyle_ng_script_source_path="$(pwd)"
  else
    declare -rx bashstyle_ng_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_bashstyle_ng() {

  local dependicies=(
    'pkgconf-pkg-config'
    'gtk-update-icon-cache'
    'bash'
    'bc'
    'make'
    'make-devel'
    'gawk'
    'grep'
    'less'
    'sed'
    'gettext'
    'texinfo'
    'intltool'
    'acpi'
    'bat'
    'libdigidocpp'
    'ffmpeg'
    'pciutils'
    'usbutils'
    'ghostscript'
    'openssh'
    'tree'
    'wget'
    'libXext'
    'xmlindent'
    'dmidecode'
    'python3'
    'python-unversioned-command'
    'python3-configobj'
    'python3-XStatic'
    'pygtk2'
    'python3-pytest-shutil'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/bashstyle-ng.txt"
  pm "$@" -- "${dependicies[@]}"

  echo "Please visit in https://nanolx.org/nanolx/bashstyle-ng"

  if [[ ! -d "${main_project_path}/application/installation/src/bashstyle-ng" ]]; then
    git clone "https://gitlab.com/Nanolx/bashstyle-ng.git" "${main_project_path}/application/installation/src/bashstyle-ng"
  fi

  cd "${main_project_path}/application/installation/src/bashstyle-ng"
  git pull
  ./make clean
  chmod +x configure
  ./configure
  ./make build
  sudo ./make install

  if ! grep '[[ -f /usr/share/bashstyle-ng/rc/bashstyle-rc ]] && source /usr/share/bashstyle-ng/rc/bashstyle-rc' ~/.bashrc; then
    echo -e "\n"'[[ -f /usr/share/bashstyle-ng/rc/bashstyle-rc ]] && source /usr/share/bashstyle-ng/rc/bashstyle-rc' | tee -a ~/.bashrc >/dev/null
  fi

}

function main_bashstyle_ng_script_source() {

  # prinf "Initialise main function of bashstyle-ng script source\n";

  install_bashstyle_ng "$@"

}

main_bashstyle_ng_script_source "$@"
