#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: Dendy-Famicom-NES
## @Creation date file: 06.12.2020, 07:25:10

[[ -z "${Dendy_Famicom_NES_script_source}" ]] && declare -rx Dendy_Famicom_NES_script_source="$BASH_SOURCE"

if [[ -z "${Dendy_Famicom_NES_script_source_path}" ]]; then
  temp_one="$(dirname ${Dendy_Famicom_NES_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx Dendy_Famicom_NES_script_source_path="$(pwd)"
  else
    declare -rx Dendy_Famicom_NES_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_Dendy_Famicom_NES() {

  local install_pkg=(
    # Имя          : fceux
    # Репозиторий  : rpmfusion-free
    # Краткое опис : A cross platform, NTSC and PAL Famicom/NES emulator
    # URL          : http://fceux.com/
    # Лицензия     : GPLv2+
    # Описание     : FCEUX is a cross platform, NTSC and PAL Famicom/NES emulator that is an
    # : evolution of the original FCE Ultra emulator. Over time FCE Ultra had
    # : separated into many separate branches.
    # :
    # : The concept behind FCEUX is to merge elements from FCE Ultra, FCEU
    # : rerecording, FCEUXD, FCEUXDSP, and FCEU-mm into a single branch of FCEU. As
    # : the X implies, it is an all-encompassing FCEU emulator that gives the best
    # : of all worlds for the casual player, the ROM-hacking community, Lua
    # : Scripters, and the Tool-Assisted Speedrun Community.
    'fceux'
    #
    # Имя          : fceux-net-server
    # Репозиторий  : rpmfusion-free
    # Краткое опис : Server for the FCEUX emulator
    # URL          : http://fceux.com/
    # Лицензия     : GPLv2+
    # Описание     : FCEUX clients can connect to this server and play multiplayer NES games over
    # : the network.
    'fceux-net-server'
    #
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/Dendy-Famicom-NES.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_Dendy_Famicom_NES_script_source() {

  # printf "Initialise main function of Dendy-Famicom-NES script source\n";

  install_Dendy_Famicom_NES "$@"

}

main_Dendy_Famicom_NES_script_source "$@"
