#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: disable-evolution
## @Creation date file: 07.09.2020, 04:08:35

declare -rx disable_evolution_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${disable_evolution_script_source})"

function main_disable_evolution_script_source() {

  # prinf "Initialise main function of disable-evolution script source\n";
  local list=(
    'evolution-addressbook-factory'
    'evolution-calendar-factory'
    'evolution-source-registry'
    'evolution-user-prompter'
    'evolution-alarm-notify'
  )

  if [[ "$(echo $(systemctl --user is-enabled ${list[@]}) | sed 's/\s//g')" != "maskedmaskedmaskedmaskedmasked" ]]; then
    echo "Services evolution* stop and masked"
    systemctl --user mask "${temp[@]}"
    sudo systemctl mask "${temp[@]}"
    find /etc/xdg/autostart -type f -name *Evolution* -exec bash -c 'X_GNOME_Autostart_disabled "$0"' '{}' \;
  else
    echo -e "Services evolution* is stop, disabled and masked.\nX_GNOME_Autostart disabled from: ${list[@]}"
  fi

}

main_disable_evolution_script_source "$@"
