#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: lua
## @Creation date file: 10.09.2020, 16:57:41

declare -rx lua_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${lua_script_source})"

function install_lua() {

  local install_pkg=(
    # Lua is a powerful light-weight programming language designed for
    #        : extending applications. Lua is also frequently used as a
    #        : general-purpose, stand-alone language. Lua is free software.
    #        : Lua combines simple procedural syntax with powerful data description
    #        : constructs based on associative arrays and extensible semantics. Lua
    #        : is dynamically typed, interpreted from bytecodes, and has automatic
    #        : memory management with garbage collection, making it ideal for
    #         : configuration, scripting, and rapid prototyping.
    #
    'lua'
    'luajit'
    'lua-guestfs'
    'lua-alt-getopt'
    'lua-argparse'
    'lua-argparse-doc'
    'lua-copas'
    'lua-coxpcall'
    'lua-cyrussasl'
    'lua-dbi'
    'lua-devel'
    'lua-event'
    'lua-event-doc'
    'lua-expat'
    'lua-filesystem'
    'lua-filesystem-compat'
    'lua-fun'
    'lua-inotify'
    'lua-ldap'
    'lua-ldap-compat'
    'lua-ldoc'
    'lua-ldoc-doc'
    'lua-lgi'
    'lua-lgi-compat'
    'lua-lgi-samples'
    'lua-librs232'
    'lua-logging'
    'lua-loop'
    'lua-loop-doc'
    'lua-lunit'
    'lua-lxc'
    'lua-markdown'
    'lua-md5'
    'lua-moonscript'
    'lua-mosquitto'
    'lua-mpack'
    'lua-penlight'
    'lua-penlight-doc'
    'lua-penlight-examples'
    'lua-prelude'
    'lua-sec'
    'lua-socket-compat'
    'lua-socket-devel'
    'lua-sql'
    'lua-sql-doc'
    'lua-sql-mysql'
    'lua-sql-postgresql'
    'lua-sql-sqlite'
    'lua-static'
    'lua-term'
    'lua-wsapi'
    'lua-xmlrpc'
    'luabind'
    'luabind-devel'
    'luadoc'
    'luajit-devel'
    'luarocks'
  )

  sudo dnf install "${install_pkg[@]}"

}

function main_lua_script_source() {

  # prinf "Initialise main function of lua script source\n";

  install_lua "$@"

}

main_lua_script_source "$@"
