#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: adobe
## @Creation date file: 11.11.2020, 02:29:49

[[ -z "${adobe_script_source}" ]] && declare -rx adobe_script_source="$BASH_SOURCE"

if [[ -z "${adobe_script_source_path}" ]]; then
  temp_one="$(dirname ${adobe_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx adobe_script_source_path="$(pwd)"
  else
    declare -rx adobe_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_adobe() {

  if [[ -z "$(check_installed_packages adobe-release-${os_version_bit})" ]]; then
    sudo dnf install "http://linuxdownload.adobe.com/adobe-release/adobe-release-${os_version_bit}-1.0-1.noarch.rpm" -y
    sudo dnf config-manager --set-enabled "adobe-linux-${os_version_bit}"
  else
    printf "Check adobe repositories is OK and activate is OK (if you haven't already disabled it manually :() \n"
  fi

}

function main_adobe_script_source() {

  # printf "Initialise main function of adobe script source\n";

  install_adobe "$@"

}

main_adobe_script_source "$@"
