#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: clear-system
## @Creation date file: 06.12.2020, 20:36:57

[[ -z "${clear_system_script_source}" ]] && declare -rx clear_system_script_source="$BASH_SOURCE"

if [[ -z "${clear_system_script_source_path}" ]]; then
  temp_one="$(dirname ${clear_system_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx clear_system_script_source_path="$(pwd)"
  else
    declare -rx clear_system_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_clear_system() {

  local install_pkg=(
    'systemd-analyze'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/clear-system.txt"
  pm "$@" -- "${install_pkg[@]}"

  sudo /etc/cron.daily/prelink

  sudo dnf clean all
  sudo pkcon refresh force
  # sudo pkcon refresh

  # rm -v -f ~/.cache/thumbnails/*/*.png ~/.thumbnails/*/*.png
  # rm -v -f ~/.cache/thumbnails/*/*/*.png ~/.thumbnails/*/*/*.png
  rm -v -r -f ~/.cache
  mkdir -p -m 0700 ~/.cache

  sudo sed -i 's/installonly_limit=3/installonly_limit=2/' /etc/dnf/dnf.conf
  # default
  # sudo sed -i 's/installonly_limit=2/installonly_limit=3/' /etc/dnf/dnf.conf

}

function main_clear_system_script_source() {

  # printf "Initialise main function of clear-system script source\n";

  install_clear_system "$@"

}

main_clear_system_script_source "$@"
