#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: diasble-tracker
## @Creation date file: 21.08.2020, 04:33:59

#
#   Декларируем имя файла
#

declare -rx diasble_tracker_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path:\n\t%s" "${main_run_script_path}"
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading:\n\t%s\n" "$(readlink -m ${diasble_tracker_script_source})"

function main_diasble_tracker_script_source() {

  local list=(
    # 'app-tracker\x2dminer\x2dfs\x2d3-autostart.service'
    # 'app-tracker\x2dminer\x2drss\x2d3-autostart.service'
    'tracker-extract-3.service'
    'tracker-extract.service'
    'tracker-miner-fs-3.service'
    'tracker-miner-fs-control-3.service'
    'tracker-miner-fs.service'
    'tracker-miner-rss-3.service'
    'tracker-miner-rss.service'
    'tracker-store.service'
    'tracker-writeback-3.service'
    'tracker-writeback.service'
    'tracker-xdg-portal-3.service'
  )

  if [[ "$(echo $(systemctl --user is-enabled ${list[@]}) | sed 's/\s//g')" != "maskedmaskedmaskedmaskedmaskedmaskedmaskedmaskedmaskedmaskedmasked" ]]; then
    printf "Stop tracker daemon: %s\n" $(tracker daemon -t all 2>/dev/null)
    printf "List services stop and masked:\n\t%s\n"
    tracker daemon -t all 2 >/dev/null
    sudo tracker daemon -t all 2 >/dev/null
    systemctl --user mask "${list[@]}"
    sudo systemctl mask "${list[@]}"
    sudo systemctl daemon-reload
    find /etc/xdg/autostart -type f -name tracker* -exec bash -c 'X_GNOME_Autostart_disabled "$0"' '{}' \;
  else
    echo -e "Tracker daemons is stop, disabled and masked.\nX_GNOME_Autostart disabled from: ${list[@]}"
  fi

}

main_diasble_tracker_script_source "$@"
