#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: disable-gnome-software-service
## @Creation date file: 07.09.2020, 04:24:24

declare -rx disable_gnome_software_service_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${disable_gnome_software_service_script_source})"

function main_disable_gnome_software_service_script_source() {

  # prinf "Initialise main function of disable-gnome-software-service script source\n";

  echo "Services packagekitd stop" # and masked"
  sudo systemctl stop packagekit
  sudo systemctl disable packagekit
  # sudo systemctl mask packagekit
  find /etc/xdg/autostart -type f -name gnome-software-service* -exec bash -c 'X_GNOME_Autostart_disabled "$0"' {} \;
  [[ "$(gsettings get org.gnome.software download-updates)" == 'true' ]] && gsettings set org.gnome.software download-updates false

}

main_disable_gnome_software_service_script_source "$@"
