#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: disable-selinux
## @Creation date file: 07.09.2020, 04:36:37

    sudo sed -i 's/^SELINUX=.*$/SELINUX=disabled/' "/etc/selinux/config"
    if ! grep -q "selinux" '/etc/default/grub'; then
      [[ -f "/etc/default/grub.back" ]] || sudo cp "/etc/default/grub" "/etc/default/grub.back"
      sudo sed -i '/rhgb quiet/s/rhgb quiet/selinux=0 rhgb quiet/' '/etc/default/grub'
      ## Реконфигурем загрузчик
      sudo grub2-mkconfig -o /boot/grub2/grub.cfg
      echo "Reconfigure grub.cfg"
    fi
    echo "SELINUX disable"

