#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: disable-selinux
## @Creation date file: 07.09.2020, 04:36:37

declare -rx disable_selinux_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${disable_selinux_script_source})"

function main_disable_selinux_script_source() {

  # prinf "Initialise main function of disable-selinux script source\n";

  if grep -Eq 'SELINUX=disabled' "/etc/selinux/config"; then
    echo "SELINUX is disabled"
  else
    sudo sed -i 's/^SELINUX=.*$/SELINUX=disabled/' "/etc/selinux/config"
    if ! grep -q "selinux" '/etc/default/grub'; then
      [[ -f "/etc/default/grub.back" ]] || sudo cp "/etc/default/grub" "/etc/default/grub.back"
      sudo sed -i '/rhgb quiet/s/rhgb quiet/selinux=0 rhgb quiet/' '/etc/default/grub'
      ## Реконфигурем загрузчик
      sudo grub2-mkconfig -o /boot/grub2/grub.cfg
      echo "Reconfigure grub.cfg"
    fi
    echo "SELINUX disable"
  fi

}

main_disable_selinux_script_source "$@"
