#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: enable-ksm
## @Creation date file: 16.10.2020, 08:20:12

[[ -z "${enable_ksm_script_source}" ]] && declare -rx enable_ksm_script_source="$BASH_SOURCE"

if [[ -z "${enable_ksm_script_source_path}" ]]; then
  temp_one="$(dirname ${enable_ksm_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx enable_ksm_script_source_path="$(pwd)"
  else
    declare -rx enable_ksm_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function main_enable_ksm_script_source() {

  # printf "Initialise main function of enable-ksm script source\n";

  local run=1
  local sleep_millisecs=1000
  local merge_across_nodes=1

  # Включаем дедупликацию страниц памяти

  if [[ -f /sys/kernel/mm/ksm/run ]]; then

    [[ $(cat /sys/kernel/mm/ksm/run) -ne ${run} ]] && echo ${run} | sudo tee /sys/kernel/mm/ksm/run >/dev/null
    if [[ $(cat /sys/kernel/mm/ksm/sleep_millisecs) -ne ${sleep_millisecs} ]]; then
      echo ${sleep_millisecs} | sudo tee /sys/kernel/mm/ksm/sleep_millisecs >/dev/null
    fi
    if [[ $(cat /sys/kernel/mm/ksm/merge_across_nodes) -ne ${merge_across_nodes} ]]; then
      echo ${merge_across_nodes} | sudo tee /sys/kernel/mm/ksm/merge_across_nodes >/dev/null
    fi

    echo "/sys/kernel/mm/ksm/run - $(cat /sys/kernel/mm/ksm/run)"
    echo "/sys/kernel/mm/ksm/sleep_millisecs - $(cat /sys/kernel/mm/ksm/sleep_millisecs)"
    echo "/sys/kernel/mm/ksm/merge_across_nodes $(cat /sys/kernel/mm/ksm/merge_across_nodes)"

    if [[ $(check_installed_packages ksmtuned) != 'ksmtuned' ]]; then
      sudo dnf install ksmtuned
      sudo sed -i 's/^#.*KSM_SLEEP_MSEC.*$/KSM_SLEEP_MSEC='"${sleep_millisecs}"'/im' '/etc/ksmtuned.conf'
      [[ $(systemctl is-enabled ksm) != 'enabled' ]] && sudo systemctl enable ksm
      [[ $(systemctl is-enabled ksmtuned) != 'enabled' ]] && sudo systemctl enable ksmtuned
      [[ $(systemctl is-active ksm) != 'active' ]] && sudo systemctl start ksm
      [[ $(systemctl is-active ksmtuned) != 'active' ]] && sudo systemctl start ksmtuned
    fi

    sudo sysctl -p

  fi

}

main_enable_ksm_script_source "$@"
