#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: host-name
## @Creation date file: 07.12.2020, 04:48:20

[[ -z "${host_name_script_source}" ]] && declare -rx host_name_script_source="$BASH_SOURCE"

if [[ -z "${host_name_script_source_path}" ]]; then
  temp_one="$(dirname ${host_name_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx host_name_script_source_path="$(pwd)"
  else
    declare -rx host_name_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

function main_host_name_script_source() {

  # printf "Initialise main function of host-name script source\n";

  if [[ "$(hostname)" != "${cfg_hostname}" ]]; then
    echo "${cfg_hostname}" | sudo tee '/etc/hostname'
    [[ -f '/etc/machine-info' ]] && sudo sed -i 's/PRETTY_HOSTNAME.*$/PRETTY_HOSTNAME='"${cfg_hostname}"'/' '/etc/machine-info'
  fi

}

main_host_name_script_source "$@"
