#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: improved-font-display-X11
## @Creation date file: 07.12.2020, 04:06:02

[[ -z "${improved_font_display_X11_script_source}" ]] && declare -rx improved_font_display_X11_script_source="$BASH_SOURCE"

if [[ -z "${improved_font_display_X11_script_source_path}" ]]; then
  temp_one="$(dirname ${improved_font_display_X11_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx improved_font_display_X11_script_source_path="$(pwd)"
  else
    declare -rx improved_font_display_X11_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_improved_font_display_X11() {

  [[ -L /etc/fonts/conf.d/11-lcdfilter-default.conf ]] || sudo ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d/
  # [[ -L /etc/fonts/conf.d/11-lcdfilter-legacy.conf ]] || sudo ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-legacy.conf /etc/fonts/conf.d/
  # [[ -L /etc/fonts/conf.d/11-lcdfilter-light.conf ]] || sudo ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-light.conf /etc/fonts/conf.d/

}

function main_improved_font_display_X11_script_source() {

  # printf "Initialise main function of improved-font-display-X11 script source\n";

  install_improved_font_display_X11 "$@"

}

main_improved_font_display_X11_script_source "$@"
