#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: network-ifaces
## @Creation date file: 08.12.2020, 00:05:08

[[ -z "${network_ifaces_script_source}" ]] && declare -rx network_ifaces_script_source="$BASH_SOURCE"

if [[ -z "${network_ifaces_script_source_path}" ]]; then
  temp_one="$(dirname ${network_ifaces_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx network_ifaces_script_source_path="$(pwd)"
  else
    declare -rx network_ifaces_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_network_ifaces() {

  local install_pkg=(

  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/network-ifaces.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_network_ifaces_script_source() {

  # printf "Initialise main function of network-ifaces script source\n";

  echo -e "\nСписок сетевых утилит и приложений:\n"
  echo -e "\tNetworkManager	Стандартный networking daemon\n"
  echo -e "\tnmtui 	Простой текстовый интерфейс (TUI) для NetworkManager\n"
  echo -e "\tnmcli 	Утилита, работающая в командной строке, которая позволяет пользователям и скриптам взаимодействовать с NetworkManager\n\tPlease read:\n\t\thttps://developer.gnome.org/NetworkManager/stable/nmcli.html\n\t\thttps://developer.gnome.org/NetworkManager/stable/\n"
  echo -e "\tcontrol-center Утилита с графическим интерфейсом оболочки GNONE\n"
  echo -e "\tnm-connection-editor\ Этот пакет содержит редактор конфигурации сети и утилиту Bluetooth-модема для использования с NetworkManager.n"

  # install_network_ifaces "$@"

}

main_network_ifaces_script_source "$@"
