#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: RUN
## @Creation date file: 07.12.2020, 04:21:13

[[ -z "${RUN_script_source}" ]] && declare -rx RUN_script_source="$BASH_SOURCE"

if [[ -z "${RUN_script_source_path}" ]]; then
  temp_one="$(dirname ${RUN_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx RUN_script_source_path="$(pwd)"
  else
    declare -rx RUN_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function main_RUN_script_source() {

  # printf "Initialise main function of RUN script source\n";

  . "${main_project_path}/system/preparation/clear-cache"
  . "${main_project_path}/system/preparation/diasble-tracker"
  . "${main_project_path}/system/preparation/disable-evolution"
  . "${main_project_path}/system/preparation/disable-selinux"
  . "${main_project_path}/system/preparation/host-conf"
  . "${main_project_path}/system/preparation/host-name"
  . "${main_project_path}/system/preparation/improved-font-display-X11"
  . "${main_project_path}/system/preparation/keyboard-conf"
  . "${main_project_path}/system/preparation/network-ifaces"
  . "${main_project_path}/system/preparation/networks"
  . "${main_project_path}/system/preparation/sshd"
  . "${main_project_path}/system/preparation/sysctl-conf"
  . "${main_project_path}/system/preparation/systemd-resolved"
  . "${main_project_path}/system/preparation/vconsole-rus-lang"
  . "${main_project_path}/system/preparation/zram-swap"

}

main_RUN_script_source "$@"
