#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: user-improvement
## @Creation date file: 11.12.2020, 04:52:34

[[ -z "${user_improvement_script_source}" ]] && declare -rx user_improvement_script_source="$BASH_SOURCE"

if [[ -z "${user_improvement_script_source_path}" ]]; then
  temp_one="$(dirname ${user_improvement_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx user_improvement_script_source_path="$(pwd)"
  else
    declare -rx user_improvement_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_user_improvement() {

  # local install_pkg=(
  # )
  # printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/user-improvement.txt"
  # pm "$@" -- "${install_pkg[@]}"

  [[ -f "/var/lib/AccountsService/icons/${cfg_user}.back" ]] || sudo cp "/var/lib/AccountsService/icons/${cfg_user}" "/var/lib/AccountsService/icons/${cfg_user}.back"
  sudo cp -f "${main_project_path}/icons/${cfg_user}.660x660.png" "/var/lib/AccountsService/icons/${cfg_user}"

}

function main_user_improvement_script_source() {

  # printf "Initialise main function of user-improvement script source\n";

  install_user_improvement "$@"

}

main_user_improvement_script_source "$@"
