#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: c
## @Creation date file: 07.11.2020, 17:12:59

[[ -z "${c_script_source}" ]] && declare -rx c_script_source="$BASH_SOURCE"

if [[ -z "${c_script_source_path}" ]]; then
  temp_one="$(dirname ${c_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx c_script_source_path="$(pwd)"
  else
    declare -rx c_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_c() {

  local install_pkg=(
    'c-development'
  )

  [[ -d "${main_project_path}/package-list" ]] || mkdir -p "${main_project_path}/package-list"
  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/c.g.txt"
  pm -g "$@" -- "${install_pkg[@]}"

  install_pkg=(
    # Краткое опис : A documentation system for C/C++
    # URL          : http://www.doxygen.nl
    # Лицензия     : GPL+
    # Описание     : Doxygen can generate an online class browser (in HTML) and/or a
    # : reference manual (in LaTeX) from a set of documented source files. The
    # : documentation is extracted directly from the sources. Doxygen can
    # : also be configured to extract the code structure from undocumented
    # : source files.
    'doxygen'
  )

}

function main_c_script_source() {

  # printf "Initialise main function of c script source\n";

  install_c "$@"

}

main_c_script_source "$@"
