#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: GtkAda
## @Creation date file: 06.12.2020, 07:00:12

[[ -z "${GtkAda_script_source}" ]] && declare -rx GtkAda_script_source="$BASH_SOURCE"

if [[ -z "${GtkAda_script_source_path}" ]]; then
  temp_one="$(dirname ${GtkAda_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx GtkAda_script_source_path="$(pwd)"
  else
    declare -rx GtkAda_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_GtkAda() {

  local install_pkg=(
    # Имя          : GtkAda
    # Репозиторий : fedora
    # Краткое опис : GTKada 2, an Ada binding to GTK+ 2
    # URL : http://libre.adacore.com/libre/tools/GtkAda/
    # Лицензия : GPLv2+
    # Описание : GtkAda is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    'GtkAda'
    #
    # Имя          : GtkAda-devel
    # Репозиторий  : fedora
    # Краткое опис : Development files for GTKada 2
    # URL          : http://libre.adacore.com/libre/tools/GtkAda/
    # Лицензия     : GPLv2+
    # Описание     : GtkAda is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    # :
    # : The GtkAda-devel package contains source code and linking information for
    # : developing applications that use GTKada 2.x. See also GtkAda3-devel.
    'GtkAda-devel'
    #
    # Имя          : GtkAda-doc
    # Репозиторий  : fedora
    # Краткое опис : Documentation for GTKada 2
    # URL          : http://libre.adacore.com/libre/tools/GtkAda/
    # Лицензия     : GPLv2+
    # Описание     : GtkAda is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    # :
    # : The GtkAda-doc package contains the documentation for GTKada 2.x.
    'GtkAda-doc'
    #
    # Имя          : GtkAda-gl
    # Репозиторий  : fedora
    # Краткое опис : GTKada 2 binding to OpenGL
    # URL          : http://libre.adacore.com/libre/tools/GtkAda/
    # Лицензия     : GPLv2+
    # Описание     : GtkAda is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    # :
    # : The GtkAda-gl package contains the GTKada binding to the OpenGL interface.
    'GtkAda-gl'
    #
    # Имя          : GtkAda-gnome
    # Репозиторий  : fedora
    # Краткое опис : GTKada 2 binding to Gnome's GUI libraries
    # URL          : http://libre.adacore.com/libre/tools/GtkAda/
    # Лицензия     : GPLv2+
    # Описание     : GtkAda is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    # :
    # : The GtkAda-gnome package contains the GTKada binding to Gnome's graphical
    # : user interface libraries.
    'GtkAda-gnome'
    #
    # Имя          : GtkAda3
    # Репозиторий  : fedora
    # Краткое опис : GTKada 3, an Ada binding to GTK+ 3
    # URL          : https://github.com/AdaCore/gtkada
    # Лицензия     : GPLv3+ with exceptions
    # Описание     : GTKada is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    'GtkAda3'
    #
    # Имя          : GtkAda3-doc
    # Репозиторий  : fedora
    # Краткое опис : Documentation for GTKada 3
    # URL          : https://github.com/AdaCore/gtkada
    # Лицензия     : GPLv3+ with exceptions
    # Описание     : GTKada is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    # :
    # : The GtkAda3-doc package contains the documentation for GTKada 3.x.
    'GtkAda3-doc'
    #
    # Имя          : GtkAda3-gl
    # Репозиторий  : fedora
    # Краткое опис : GTKada 3 binding to OpenGL
    # URL          : https://github.com/AdaCore/gtkada
    # Лицензия     : GPLv3+ with exceptions
    # Описание     : GTKada is an Ada binding to the graphical toolkit GTK+. It allows you to
    # : develop graphical user interfaces in Ada using GTK+.
    # :
    # : The GtkAda3-gl package contains the GTKada binding to the OpenGL interface.
    'GtkAda3-gl'
    #
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/GtkAda.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_GtkAda_script_source() {

  # printf "Initialise main function of GtkAda script source\n";

  install_GtkAda "$@"

}

main_GtkAda_script_source "$@"
