#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: vala
## @Creation date file: 11.12.2020, 05:44:37

[[ -z "${vala_script_source}" ]] && declare -rx vala_script_source="$BASH_SOURCE"

if [[ -z "${vala_script_source_path}" ]]; then
  temp_one="$(dirname ${vala_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx vala_script_source_path="$(pwd)"
  else
    declare -rx vala_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_vala() {

  local install_pkg=(
    # Имя          : vala
    # Репозиторий  : updates
    # Краткое опис : A modern programming language for GNOME
    # URL          : https://wiki.gnome.org/Projects/Vala
    # Лицензия     : LGPLv2+ and BSD
    # Описание     : Vala is a new programming language that aims to bring modern programming
    #              : language features to GNOME developers without imposing any additional
    #              : runtime requirements and without using a different ABI compared to
    #              : applications and libraries written in C.
    #              :
    #              : valac, the Vala compiler, is a self-hosting compiler that translates
    #              : Vala source code into C source and header files. It uses the GObject
    #              : type system to create classes and interfaces declared in the Vala source
    #              : code. It's also planned to generate GIDL files when gobject-
    #              : introspection is ready.
    #              :
    #              : The syntax of Vala is similar to C#, modified to better fit the GObject
    #              : type system.
    'vala'
    # Имя          : vala-doc
    # Репозиторий  : updates
    # Краткое опис : Documentation for vala
    # URL          : https://wiki.gnome.org/Projects/Vala
    # Лицензия     : LGPLv2+
    # Описание     : Vala is a new programming language that aims to bring modern programming
    #              : language features to GNOME developers without imposing any additional
    #              : runtime requirements and without using a different ABI compared to
    #              : applications and libraries written in C.
    #              :
    #              : This package contains documentation in a devhelp HTML book.
    'vala-doc'
    # Имя          : valadoc
    # Репозиторий  : updates
    # Краткое опис : Vala documentation generator
    # URL          : https://wiki.gnome.org/Projects/Vala
    # Лицензия     : LGPLv2+ and BSD
    # Описание     : Valadoc is a documentation generator for generating API documentation from Vala
    #              : source code.
    'valadoc'
    # Имя          : valadoc-devel
    # Репозиторий  : updates
    # Краткое опис : Development files for valadoc
    # URL          : https://wiki.gnome.org/Projects/Vala
    # Лицензия     : LGPLv2+ and BSD
    # Описание     : Valadoc is a documentation generator for generating API documentation from Vala
    #              : source code.
    #              :
    #              : The valadoc-devel package contains libraries and header files for
    #              : developing applications that use valadoc.
    'valadoc-devel'
    # Имя : augeas-vala
    # Репозиторий : fedora
    # Краткое опис : Vala bindings for augeas
    # URL : http://www.gitorious.org/valastuff/augeas-vala/
    # Лицензия : LGPLv2+
    # Описание : Vala bindings for augeas.
    'augeas-vala'
    # Имя          : libguestfs-vala
    # Репозиторий  : fedora
    # Краткое опис : Vala for libguestfs
    # URL          : http://libguestfs.org/
    # Лицензия     : LGPLv2+
    # Описание     : libguestfs-vala contains GObject bindings for libguestfs.
    'libguestfs-vala'
    # Имя          : libinsane-vala
    # Репозиторий  : updates
    # Краткое опис : Vala bindings for libinsane
    # URL          : https://doc.openpaper.work/libinsane/latest/
    # Лицензия     : LGPLv3+
    # Описание     : Vala bindings for libinsane.
    'libinsane-vala'
    # Имя          : libvala-devel
    # Репозиторий  : updates
    # Краткое опис : Development files for libvala
    # URL          : https://wiki.gnome.org/Projects/Vala
    # Лицензия     : LGPLv2+ and BSD
    # Описание     : Vala is a new programming language that aims to bring modern programming
    #              : language features to GNOME developers without imposing any additional
    #              : runtime requirements and without using a different ABI compared to
    #              : applications and libraries written in C.
    #              :
    #              : This package contains development files for libvala. This is not
    #              : necessary for using the vala compiler.
    'libvala-devel'
    # Имя          : libvirt-designer-vala
    # Репозиторий  : fedora
    # Краткое опис : Libvirt designer vala language bindings
    # URL          : http://libvirt.org/
    # Лицензия     : LGPLv2+
    # Описание     : This package provides the libvirt configuration designer vala
    #              : language binding
    'libvirt-designer-vala'
    # Имя          : spice-gtk3-vala
    # Репозиторий  : updates
    # Краткое опис : Vala bindings for the spice-gtk-3.0 library
    # URL          : https://www.spice-space.org/spice-gtk.html
    # Лицензия     : LGPLv2+
    # Описание     : A module allowing use of the spice-gtk-3.0 widget from vala
    'spice-gtk3-vala'
    # Имя          : telepathy-glib-vala
    # Репозиторий  : fedora
    # Краткое опис : Vala bindings for telepathy-glib
    # URL          : http://telepathy.freedesktop.org/wiki/FrontPage
    # Лицензия     : LGPLv2+
    # Описание     : Vala bindings for telepathy-glib.
    'telepathy-glib-vala'
    # Имя          : vim-syntastic-vala
    # Репозиторий  : fedora
    # Краткое опис : A syntax checker for vala programming language
    # URL          : https://github.com/scrooloose/syntastic
    # Лицензия     : WTFPL
    # Описание     : Allows checking vala sources files.
    'vim-syntastic-vala'
    # Имя          : xfce4-vala
    # Репозиторий  : fedora
    # Краткое опис : Vala bindings for the Xfce framework
    # URL          : http://wiki.xfce.org/vala-bindings
    # Лицензия     : LGPLv2+
    # Описание     : Xfce4 Vala provides bindings for the Xfce framework
    # 'xfce4-vala'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/vala.txt"
  pm "$@" -- "${install_pkg[@]}" -x nspr-devel

}

function main_vala_script_source() {

  # printf "Initialise main function of vala script source\n";

  install_vala "$@"

}

main_vala_script_source "$@"
