#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: index
## @Creation date file: 13.09.2020, 11:31:11

declare -rx index_script_source="$BASH_SOURCE"

temp_one="$(dirname ${index_script_source})"
if [[ "${temp_one}" == '.' ]]; then
  declare -rx index_script_source_path="$(pwd)"
else
  declare -rx index_script_source_path="${temp_one}"
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${index_script_source})"

function main_index_script_source() {

  # prinf "Initialise main function of index script source\n";
  [[ -z "${nginx_script_source_path}" ]] && local nginx_script_source_path='.'
  [[ -z "$rev_timestamp" ]] && local rev_timestamp="$(cat ${nginx_script_source_path}/rev-timestamp.txt)"

  cat <<EOF | sudo tee /usr/share/nginx/html/index.html >/dev/null
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="ru">
<head>
  <title>Zero page</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="description" content="${cfg_full_org}. Zero page of Server: ${cfg_org} - 23.06.06 - rev: ${rev_timestamp}" />
  <meta name="keywords" content="${cfg_full_org}, Server, Contacts, License" />
  <meta name="author" content="${cfg_org}" />
  <meta name="email" content="${cfg_email}" />
  <link rel="manifest" href="manifest.json">
  <style type="text/css">
    /*<![CDATA[*/
      body {
        padding: 0px;
        margin: 0px;
        border-width: 0px;
        background-color: white;
        font-size: 1.2em;
      }

      body, .app {
        width: 100vw;
        height: 100vh;
      }

      .app {

        display: flex;
	      display: -webkit-box;
	      display: -webkit-flex;
	      display: -ms-flexbox;

      }

      .app, .org, .footer {
        flex-direction: column;
	      -webkit-box-orient: vertical;
	      -webkit-box-direction: normal;
	      -webkit-flex-direction: column;
	      -ms-flex-direction: column;

        justify-content: center;
	      -webkit-box-pack: justify;
	      -webkit-justify-content: center;
	      -ms-flex-pack: justify;

        align-content: center;
	      -webkit-align-content: center;
	      -ms-flex-line-pack: distribute;

        align-items: center
	      -webkit-box-align: center;
	      -webkit-align-items: center;
	      -ms-flex-align: center;
      }

      .org {
        padding: 10px;
        /***
          border-bottom: 1px solid rgba(0,0,0,0.1);
          */
        text-align: center;
      }
      .footer {
        text-align: center;
      }
      .logo {
        margin: 5px 5px 25px 5px;
        width: 64px;
        height: 64px;
      }
      .mail-link {
        margin-top: 40px;
        width: 32px;
        height: 32px;
      }
      a {
        color: #4285F4;
      }
      .zero-page {
        font-size: 1.4em;
        font-weight: bold;
      }
      #license {
        display: none;
        width: 50vw;
        margin-top: 40px;
        color: rgba(150,150,150,1);
        font-size: 0.5em;
      }
    /*]]>*/
  </style>
</head>
<body>
  <div class="app">
    <img class="logo" src="logo.png"></img>
    <div class="org">
      <span class="zero-page">Zero page</span>
      <h1><span style="color: #f5bb09;">S</span>ensor-<span style="color: #3ea852;">D</span>ream <span style="color: #ea4334;">B</span>oxed <span style="color: #4285f4;">S</span>ystem</h1>
    </div>
    <div class="footer">
      Server: <strong><span style="color: #f5bb09;">S</span><span style="color: #3ea852;">D</span><span style="color: #ea4334;">B</span><span style="color: #4285f4;">S</span></strong> - <strong>23.06.06</strong> - rev: ${rev_timestamp}<br />
      <a href="mailto: ${cfg_email}"><img class="mail-link" src="mail-link.png"></img></a>
      <br />
      <div id="license">
        @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
        <br />
        @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
        <br />
        @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
        <br />
        Licensed under the Apache License, Version 2.0 (the "License");
        <br />
        You may not use this file except in compliance with the License.
        <br />
        You may obtain a copy of the License at
        <br />
        http://www.apache.org/licenses/LICENSE-2.0
        <br />
        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
      </div>
      <br />
      <!-- Double page: <a href="https://we-docs.sensor-dream.ru">sensor-dream.ru</a> -->
    </div>
  </div>
</body>
</html>
EOF

}

main_index_script_source "$@"
