#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: index
## @Creation date file: 13.09.2020, 11:31:11

declare -rx index_script_source="$BASH_SOURCE"

temp_one="$(dirname ${index_script_source})"
if [[ "${temp_one}" == '.' ]]; then
    declare -rx index_script_source_path="$(pwd)"
else
    declare -rx index_script_source_path="${temp_one}"
fi

if [[ -z "${main_run_script_path}" ]]; then
    declare -rx main_run_script_path="$(pwd)"
    printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
    check=1
    while [[ "${check}" -eq 1 ]]; do
        if [[ ! -f 'main.cfg' ]]; then
            if [[ "$(pwd)" != "/" ]]; then
                cd ../
            else
                cd ${main_run_script_path}
                check=0
                echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
                tput sgr0
                exit 1
            fi
        else
            check=0
            declare -rx main_project_path="$(pwd)"
            . "${main_project_path}/main.cfg" "$@"
            cd "${main_run_script_path}"
        fi
    done
fi

printf "Loading: %s\n" "$(readlink -m ${index_script_source})"

function main_index_script_source() {

    # prinf "Initialise main function of index script source\n";
    [[ -z "${nginx_script_source_path}" ]] && local nginx_script_source_path='.'
    [[ -z "$rev_timestamp" ]] && local rev_timestamp="$(cat ${nginx_script_source_path}/rev-timestamp.txt)"

    cat <<EOF | sudo tee /usr/share/nginx/html/index.html >/dev/null
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="ru">
<head>
  <title>Zero page</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="description" content="${cfg_full_org}. Zero page of Server: ${cfg_org} - 23.06.06 - rev: ${rev_timestamp}" />
  <meta name="keywords" content="${cfg_full_org}, Server, Contacts, License" />
  <meta name="author" content="${cfg_org}" />
  <meta name="email" content="${cfg_email}" />
  <link rel="icon" href="https://sensor-dream.ru/favicon.png" type="image/png">
  <link rel="manifest" href="manifest.json">
  <style type="text/css">
    /*<![CDATA[*/
      body {
        padding: 0px;
        margin: 0px;
        border-width: 0px;
        background-color: white;
        font-size: 1.2em;
      }

      body, .app, .wgl-app {
        width: 100vw;
        height: 100vh;
      }

      .app {

        display: flex;
	      display: -webkit-box;
	      display: -webkit-flex;
	      display: -ms-flexbox;
      }

      .app, .org, .footer {
        flex-direction: column;
	      -webkit-box-orient: vertical;
	      -webkit-box-direction: normal;
	      -webkit-flex-direction: column;
	      -ms-flex-direction: column;

        justify-content: center;
	      -webkit-box-pack: justify;
	      -webkit-justify-content: center;
	      -ms-flex-pack: justify;

        align-content: center;
	      -webkit-align-content: center;
	      -ms-flex-line-pack: distribute;

        align-items: center
	      -webkit-box-align: center;
	      -webkit-align-items: center;
	      -ms-flex-align: center;
      }

      .org {
        padding: 10px;
        /***
          border-bottom: 1px solid rgba(0,0,0,0.1);
          */
        text-align: center;
      }
      .footer {
        text-align: center;
      }
      .logo {
        margin: 5px 5px 25px 5px;
        width: 64px;
        height: 64px;
      }
      .mail-link {
        margin-top: 4px;
        width: 32px;
        height: 32px;
      }
      #statcounter {
        padding-top: 10px;
      }
      a, a:visited, a:link, a:active, a:hover {
        color: #4285F4;
        text-decoration: none;
      }
      .zero-page {
        font-size: 1.4em;
        font-weight: bold;
      }
      #license {
        display: none;
        width: 50vw;
        margin-top: 40px;
        color: rgba(150,150,150,1);
        font-size: 0.5em;
      }
    /*]]>*/
    .wgl-app {
	position: absolute;
	background-color: transparent;
	z-index: -1;
    }
  </style>
</head>
<body>
  <canvas id="wgl-app" class="wgl-app"></canvas>
  <div class="app" id="app">
    <img class="logo" src="logo.png"></img>
    <div class="org">
      <span class="zero-page">Zero page.</span>
      <h1><span style="color: #f5bb09;">S</span>ensor-<span style="color: #3ea852;">D</span>ream <span style="color: #ea4334;">B</span>oxed <span style="color: #4285f4;">S</span>ystem</h1>
      Lets go the <a href="https://we-docs.sensor-dream.ru">https://we-docs.sensor-dream.ru</a>
    </div>
    <div class="footer">
      Server: <strong><span style="color: #f5bb09;">S</span><span style="color: #3ea852;">D</span><span style="color: #ea4334;">B</span><span style="color: #4285f4;">S</span></strong> - <strong>23.06.06</strong> - rev: ${rev_timestamp}<br />
      <br />Send message to <br />&#9660;<br />
      <a href="mailto: ${cfg_email}"><img class="mail-link" src="mail-link.png"></img></a><br />
      <!-- Yandex.Metrika counter -->
	 <script type="text/javascript" >
	    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
	    m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
	    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

	    ym(87100723, "init", {
	         clickmap:true,
	         trackLinks:true,
	         accurateTrackBounce:true
	    });
	 </script>
	 <noscript><div><img src="https://mc.yandex.ru/watch/87100723" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
      <!-- /Yandex.Metrika counter -->
      <!-- Default Statcounter code for My domain sensor-dream.ru https://sensor-dream.ru -->
        <script type="text/javascript">
          var sc_project=12511240; 
          var sc_invisible=0; 
          var sc_security="3a841b1e"; 
          var sc_client_storage="disabled"; 
          var scJsHost = "https://";
          document.write("<sc"+"ript type='text/javascript' src='" + scJsHost+"statcounter.com/counter/counter.js'></" + "script>");
        </script>
        <noscript><div class="statcounter"><a title="Web Analytics" href="https://statcounter.com/" target="_blank"><img class="statcounter" src="https://c.statcounter.com/12511240/0/3a841b1e/0/" alt="Web Analytics"></a></div></noscript>
      <!-- End of Statcounter Code -->
      <br />
      <div id="license">
        @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
        <br />
        @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
        <br />
        @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
        <br />
        Licensed under the Apache License, Version 2.0 (the "License");
        <br />
        You may not use this file except in compliance with the License.
        <br />
        You may obtain a copy of the License at
        <br />
        http://www.apache.org/licenses/LICENSE-2.0
        <br />
        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
      </div>
      <br />
      <!-- Double page: <a href="https://we-docs.sensor-dream.ru">sensor-dream.ru</a> -->
    </div>
  </div>
  <!-- <script src="https://ylei753tkpb.montastic.io/embed/script.js"></script> -->
</body>
</html>
EOF

}

main_index_script_source "$@"
