#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: list-module
## @Creation date file: 12.09.2020, 09:25:34

declare -rx list_module_script_source="$BASH_SOURCE"

printf "Loading: %s\n" "$(readlink -m ${list_module_script_source})"

declare -A local list_module=(
  ['ngx_devel_kit']='https://github.com/vision5/ngx_devel_kit.git --add-module yes'
  ['headers-more-nginx-module']='https://github.com/openresty/headers-more-nginx-module.git --add-dynamic-module yes'
  ['ngx_http_geoip2_module']='https://github.com/leev/ngx_http_geoip2_module.git --add-dynamic-module yes'
  ['set-misc-nginx-module']='https://github.com/openresty/set-misc-nginx-module.git --add-dynamic-module yes'
  ['ngx_http_substitutions_filter_module']='git://github.com/yaoweibin/ngx_http_substitutions_filter_module.git --add-dynamic-module yes'
  ['memc-nginx-module']='https://github.com/openresty/memc-nginx-module.git --add-dynamic-module yes'
  ['srcache-nginx-module']='https://github.com/openresty/srcache-nginx-module.git --add-dynamic-module yes'
  ['nginx-module-vts']='https://github.com/vozlt/nginx-module-vts.git --add-dynamic-module no'
  ['nginx-push-stream-module']='https://github.com/wandenberg/nginx-push-stream-module.git --add-dynamic-module yes'
  ['lua-nginx-module']='https://github.com/openresty/lua-nginx-module.git --add-dynamic-module no'
)
