#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: zero-webmanifest
## @Creation date file: 24.09.2020, 02:29:55

declare -rx zero_webmanifest_script_source="$BASH_SOURCE"

temp_one="$(dirname ${zero_webmanifest_script_source})"
if [[ "${temp_one}" == '.' ]]; then
  declare -rx zero_webmanifest_script_source_path="$(pwd)"
else
  declare -rx zero_webmanifest_script_source_path="${temp_one}"
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${zero_webmanifest_script_source})"

function main_zero_webmanifest_script_source() {

  # prinf "Initialise main function of zero-webmanifest script source\n";

  [[ -z "${nginx_script_source_path}" ]] && local nginx_script_source_path='.'
  [[ -z "$rev_timestamp" ]] && local rev_timestamp="$(cat ${nginx_script_source_path}/rev-timestamp.txt)"

  cat <<EOF | sudo tee /usr/share/nginx/html/manifest.json >/dev/null
{
  "short_name": "SDBS",
  "name": "Sensor-Dream Boxed System",
  "description": "Sensor-Dream Boxed System. Zero page of Server: SDBS - 23.06.06 - rev: $rev_timestamp",
  "icons": [
    {
      "src": "/favicon.ico",
      "type": "image/x-icon",
      "sizes": "64x64"
    },
    {
      "src": "/logo.png",
      "type": "image/png",
      "sizes": "196x196"
    },
    {
      "src": "/mail-link.png",
      "type": "image/png",
      "sizes": "900x900"
    }
  ],
  "start_url": "/",
  "background_color": "#fff",
  "display": "standalone",
  "scope": "/",
  "theme_color": "#fff"
}
EOF

}

main_zero_webmanifest_script_source "$@"
