#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: cfg-network-information
## @Creation date file: 15.10.2020, 17:40:04

[[ -z "${cfg_network_information_script_source}" ]] && declare -rx cfg_network_information_script_source="$BASH_SOURCE"

if [[ -z "${cfg_network_information_script_source_path}" ]]; then
  temp_one="$(dirname ${cfg_network_information_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx cfg_network_information_script_source_path="$(pwd)"
  else
    declare -rx cfg_network_information_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function main_cfg_network_information_script_source() {

  # prinf "Initialise main function of cfg-network-information script source\n";

  echo
  echo -n "Введите локальный IP: "
  read cfg_local_ip
  if [[ -z "${cfg_local_ip}" ]]; then
    echo "ЕПТА выходим"
    exit
  fi
  echo
  echo -n "РВведите маску диапазонов: "
  read cfg_local_ip_mask
  if [[ -z "${cfg_local_ip_mask}" ]]; then
    echo "ЕПТА выходим"
    exit
  fi
  echo
  echo -n "Введите шлюз "
  read cfg_local_ip_shluze_epta
  if [[ -z "${cfg_local_ip_shluze_epta}" ]]; then
    echo "ЕПТА выходим"
    exit
  fi
  cat <<EOF >"${main_project_path}/hidden/cfg-network-information"
declare -rx cfg_local_ip="${cfg_local_ip}";
declare -rx cfg_local_ip_mask="${cfg_local_ip_mask}";
declare -rx cfg_local_ip_shluze_epta="${cfg_local_ip_shluze_epta}"
EOF

  chmod 0600 "${main_project_path}/hidden/cfg-network-information"

}

main_cfg_network_information_script_source "$@"
