#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: clamav
## @Creation date file: 07.11.2020, 06:23:47

[[ -z "${clamav_script_source}" ]] && declare -rx clamav_script_source="$BASH_SOURCE"

if [[ -z "${clamav_script_source_path}" ]]; then
  temp_one="$(dirname ${clamav_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx clamav_script_source_path="$(pwd)"
  else
    declare -rx clamav_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_clamav() {

  local install_pkg=(
    # : Clam AntiVirus is an anti-virus toolkit for UNIX. The main purpose of this
    # : software is the integration with mail servers (attachment scanning). The
    # : package provides a flexible and scalable multi-threaded daemon, a command
    # : line scanner, and a tool for automatic updating via Internet. The programs
    # : are based on a shared library distributed with the Clam AntiVirus package,
    # : which you can use with your own software. The virus database is based on
    # : the virus database from OpenAntiVirus, but contains additional signatures
    # : (including signatures for popular polymorphic viruses, too) and is KEPT UP
    # : TO DATE.
    'clamav'
    'clamav-data'
    'clamav-filesystem'
    'clamav-lib'
    'clamav-update'
    'clamav-unofficial-sigs'
    'clamav-devel'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/clamav.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_clamav_script_source() {

  # printf "Initialise main function of clamav script source\n";

  install_clamav "$@"

}

main_clamav_script_source "$@"
