#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: design-of-electrical-circuits
## @Creation date file: 06.10.2020, 20:07:48

[[ -z "${design_of_electrical_circuits_script_source}" ]] && declare -rx design_of_electrical_circuits_script_source="$BASH_SOURCE"

if [[ -z "${design_of_electrical_circuits_script_source_path}" ]]; then
  temp_one="$(dirname ${design_of_electrical_circuits_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx design_of_electrical_circuits_script_source_path="$(pwd)"
  else
    declare -rx design_of_electrical_circuits_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_design_of_electrical_circuits() {

  local install_pkg=(
    'qelectrotech'
  )

  sudo dnf install "${install_pkg[@]}" "$@"

}

function main_design_of_electrical_circuits_script_source() {

  # prinf "Initialise main function of design-of-electrical-circuits script source\n";

  install_design_of_electrical_circuits "$@"

}

main_design_of_electrical_circuits_script_source "$@"
