#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: dm
## @Creation date file: 17.12.2020, 15:20:14

[[ -z "${dm_script_source}" ]] && declare -rx dm_script_source="$BASH_SOURCE"

if [[ -z "${dm_script_source_path}" ]]; then
  temp_one="$(dirname ${dm_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx dm_script_source_path="$(pwd)"
  else
    declare -rx dm_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_dm() {

  local install_pkg=(
    # Имя          : sddm
    # Репозиторий  : fedora
    # Краткое опис : QML based X11 desktop manager
    # URL          : https://github.com/sddm/sddm
    # Лицензия     : GPLv2+
    # Описание     : SDDM is a modern display manager for X11 aiming to be fast, simple and
    #              : beautiful. It uses modern technologies like QtQuick, which in turn gives the
    #              : designer the ability to create smooth, animated user interfaces.
    'sddm'
    #
    # Имя          : sddm-breeze
    # Репозиторий  : updates
    # Краткое опис : SDDM breeze theme
    # URL          : https://cgit.kde.org/plasma-workspace.git
    # Лицензия     : GPLv2+
    # Описание     : SDDM breeze theme.
    'sddm-breeze'
    #
    # Имя          : sddm-themes
    # Репозиторий  : fedora
    # Краткое опис : SDDM Themes
    # URL          : https://github.com/sddm/sddm
    # Лицензия     : GPLv2+
    # Описание     : A collection of sddm themes, including: elarun, maldives, maya
    'sddm-themes'
    #
    # Имя          : sddm-kcm
    # Репозиторий  : updates
    # Краткое опис : SDDM KDE configuration module
    # URL          : https://cgit.kde.org/sddm-kcm.git
    # Лицензия     : GPLv2+
    # Описание     : This is a System Settings configuration module for configuring the
    #              : SDDM Display Manager
    'sddm-kcm'
    #
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/dm.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_dm_script_source() {

  # printf "Initialise main function of dm script source\
  install_dm "$@"
  # sudo systemctl disable gdm
  # sudo systemctl enable sddm
  # sudo reboot

  # sudo systemctl start sddm

}

main_dm_script_source "$@"
