#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: games-pack
## @Creation date file: 13.11.2020, 04:34:17

[[ -z "${games_pack_script_source}" ]] && declare -rx games_pack_script_source="$BASH_SOURCE"

if [[ -z "${games_pack_script_source_path}" ]]; then
  temp_one="$(dirname ${games_pack_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx games_pack_script_source_path="$(pwd)"
  else
    declare -rx games_pack_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_games_pack() {

  local install_pkg=(
    # Краткое опис : An open-source port of Prince of Persia
    # URL          : https://github.com/NagyD/SDLPoP
    # Описание     : SDLPoP is an open-source port of Prince of Persia, based on the disassembly
    # : of the DOS version.
    'SDLPoP'
    # Имя          : workrave
    # Репозиторий  : fedora
    # Краткое опис : Program that assists in the recovery and prevention of RSI
    # URL          : http://www.workrave.org/
    # Лицензия     : GPLv3+
    # Описание     : Workrave is a program that assists in the recovery and prevention of
    # : Repetitive Strain Injury (RSI). The program frequently alerts you to
    # : take micro-pauses, rest breaks and restricts you to your daily limit.
    'workrave'

  )

  [[ -d "${main_project_path}/package-list" ]] || mkdir -p "${main_project_path}/package-list"
  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/games-pack.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_games_pack_script_source() {

  # printf "Initialise main function of games-pack script source\n";

  install_games_pack "$@"

}

main_games_pack_script_source "$@"
