#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: gnome-shell
## @Creation date file: 20.10.2020, 15:01:04

[[ -z "${gnome_shell_script_source}" ]] && declare -rx gnome_shell_script_source="$BASH_SOURCE"

if [[ -z "${gnome_shell_script_source_path}" ]]; then
  temp_one="$(dirname ${gnome_shell_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx gnome_shell_script_source_path="$(pwd)"
  else
    declare -rx gnome_shell_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_gnome_shell() {

  local install_pkg=(
    'xorg-x11-utils'
    'glib2-devel'
    'ImageMagick'
    'gnome-tweaks'
    'gnome-extensions-app'
    'gnome-shell-extension-appindicator'
    'gnome-shell-extension-activities-configurator'
    'gnome-shell-extension-apps-menu'
    'gnome-shell-extension-argos'
    'gnome-shell-extension-auto-move-windows'
    # 'gnome-shell-extension-bubblemail'
    'gnome-shell-extension-desktop-icons'
    'gnome-shell-extension-material-shell'
    'gnome-shell-extension-ibus-font'
    'gnome-shell-extension-historymanager-prefix-search'
    # 'gnome-shell-extension-gsconnect'
    # 'gnome-shell-extension-gpaste'
    'gnome-shell-extension-openweather'
    'gnome-shell-extension-screenshot-window-sizer'
    'gnome-shell-extension-dash-to-dock'
    'gnome-shell-extension-do-not-disturb-button'
    'gnome-shell-extension-gamemode'
    'gnome-shell-extension-topicons-plus'
    'gnome-shell-extension-system-monitor-applet'
    'gnome-shell-extension-suspend-button'
    # 'gnome-shell-extension-refresh-wifi'
    # 'gnome-shell-extension-disconnect-wifi'
    # 'gnome-shell-extension-pomodoro'
    # 'gnome-shell-extension-pidgin'
    'gnome-shell-extension-native-window-placement'
    'gnome-shell-extension-media-player-indicator'
    'gnome-shell-extension-netspeed'
    'gnome-shell-extension-freon'
    'gnome-shell-extension-emoji-selector'
    'gnome-shell-extension-unite'
    'gnome-shell-extension-user-theme'
    'gnome-shell-extension-windowoverlay-icons'
    'gnome-shell-extension-windowsNavigator'
    'gnome-shell-extension-workspace-indicator'
    'gnome-shell-extension-drive-menu'
    'gnome-shell-extension-pop-shell'
    'gnome-shell-extension-pop-shell-shortcut-overrides'
    'gtk-update-icon-cache'
    'mingw64-gtk-update-icon-cache'
    # GNOME Desktop theme optimized for small displays
    'clearlooks-compact-gnome-theme'
    'gnome-themes-extra'
    ## theme of Xenlism Wildfire
    # 'xenlism-wildfire'
    # 'xenlism-wildfire-day'
    # 'xenlism-wildfire-friday'
    # 'xenlism-wildfire-midnight'
    # 'xenlism-wildfire-monday'
    # 'xenlism-wildfire-night'
    # 'xenlism-wildfire-saturday'
    # 'xenlism-wildfire-sunday'
    # 'xenlism-wildfire-thursday'
    # 'xenlism-wildfire-tuesday'
    # 'xenlism-wildfire-wednesday'
    # 'gnome-shell-theme-selene'
    'gnome-shell-theme-yaru'
    'gnome-shell-theme-flat-remix'
    'flat-remix-gtk3-theme'
    'flat-remix-theme'
    'paper-icon-theme'
    'papirus-icon-theme'
    'elementary-icon-theme-gimp-palette'
    'flat-remix-icon-theme'
    'adwaita-cursor-theme'
    # 'la-capitaine-cursor-theme'
  )

  pm "$@" -- "${install_pkg[@]}"

  echo "Run dnf search gtk | grep theme and dnf search shell-theme and dnf search icon-theme and dnf search cursor-theme"
  echo 'Please read https://www.gnome-look.org for theme and ...'
  echo
  echo "Local share themes path: ~/.local/share/themes"
  echo "Local share icons path: ~/.local/share/icons"
  echo
  echo 'Please read https://extensions.gnome.org/extension/97/coverflow-alt-tab'
  echo 'Please read https://extensions.gnome.org/extension/3628/arcmenu/'
  echo 'Please read https://extensions.gnome.org/extension/3780/ddterm/'

}

function main_gnome_shell_script_source() {

  # printf "Initialise main function of gnome-shell script source\n";

  install_gnome_shell "$@"

}

main_gnome_shell_script_source "$@"
