#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: grafana
## @Creation date file: 18.10.2020, 15:38:28

[[ -z "${grafana_script_source}" ]] && declare -rx grafana_script_source="$BASH_SOURCE"

if [[ -z "${grafana_script_source_path}" ]]; then
  temp_one="$(dirname ${grafana_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx grafana_script_source_path="$(pwd)"
  else
    declare -rx grafana_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_grafana() {

  # Read https://devconnected.com/how-to-setup-grafana-and-prometheus-on-linux/#b_Configuring_NGINX_as_a_reverse_proxy

  local install_pkg=(
    'grafana'
    'grafana-pcp'
    'ceph-grafana-dashboards'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort >"${main_project_path}/package-list/grafana.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_grafana_script_source() {

  # printf "Initialise main function of grafana script source\n";

  install_grafana "$@"

}

main_grafana_script_source "$@"
