#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: gvfs
## @Creation date file: 23.10.2020, 18:41:26

[[ -z "${gvfs_script_source}" ]] && declare -rx gvfs_script_source="$BASH_SOURCE"

if [[ -z "${gvfs_script_source_path}" ]]; then
  temp_one="$(dirname ${gvfs_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx gvfs_script_source_path="$(pwd)"
  else
    declare -rx gvfs_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_gvfs() {

  # Краткое опис : Backends for the gio framework in GLib
  # URL          : https://wiki.gnome.org/Projects/gvfs
  # Лицензия     : GPLv3 and LGPLv2+ and BSD and MPLv2.0
  # Описание     : The gvfs package provides backend implementations for the gio
  #               : framework in GLib. It includes ftp, sftp, cifs.

  local install_pkg=(
    'gvfs'
    'gvfs-afc'
    'gvfs-afp'
    'gvfs-archive'
    'gvfs-client'
    'gvfs-fuse'
    'gvfs-goa'
    'gvfs-gphoto2'
    'gvfs-mtp'
    'gvfs-smb'
    'gvfs-nfs'
    'gvfs-devel'
    'gvfs-tests'
  )

  pm "$@" -- "${install_pkg[@]}"

}

function main_gvfs_script_source() {

  # printf "Initialise main function of gvfs script source\n";

  install_gvfs "$@"

}

main_gvfs_script_source "$@"
