#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: inkscape
## @Creation date file: 04.12.2020, 22:19:42

[[ -z "${inkscape_script_source}" ]] && declare -rx inkscape_script_source="$BASH_SOURCE"

if [[ -z "${inkscape_script_source_path}" ]]; then
  temp_one="$(dirname ${inkscape_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx inkscape_script_source_path="$(pwd)"
  else
    declare -rx inkscape_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_inkscape() {

  local install_pkg=(
    # Имя          : inkscape
    # Репозиторий  : @System
    # Из репозитор : fedora
    # Краткое опис : Vector-based drawing program using SVG
    # URL          : https://inkscape.org/
    # Лицензия     : GPLv2+ and CC-BY
    # Описание     : Inkscape is a vector graphics editor, with capabilities similar to
    # : Illustrator, CorelDraw, or Xara X, using the W3C standard Scalable Vector
    # : Graphics (SVG) file format.  It is therefore a very useful tool for web
    # : designers and as an interchange format for desktop publishing.
    # :
    # : Inkscape supports many advanced SVG features (markers, clones, alpha
    # : blending, etc.) and great care is taken in designing a streamlined
    # : interface. It is very easy to edit nodes, perform complex path operations,
    # : trace bitmaps and much more.
    'inkscape'
    'inkscape-view'
    'inkscape-psd'
    'inkscape-docs'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/inkscape.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_inkscape_script_source() {

  # printf "Initialise main function of inkscape script source\n";

  install_inkscape "$@"

}

main_inkscape_script_source "$@"
