#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: kernel
## @Creation date file: 15.10.2020, 17:28:17

[[ -z "${kernel_script_source}" ]] && declare -rx kernel_script_source="$BASH_SOURCE"

if [[ -z "${kernel_script_source_path}" ]]; then
  temp_one="$(dirname ${kernel_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx kernel_script_source_path="$(pwd)"
  else
    declare -rx kernel_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_kernel() {

  local install_pkg=(
    kernel
    kernel-core
    kernel-cross-headers
    kernel-devel
    kernel-headers
    kernel-modules
    kernel-modules-extra
    kernel-modules-internal
    kernel-rpm-macros
    kernel-srpm-macros
    kernel-tools
    kernel-tools-libs
    kernel-tools-libs-devel
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/kernel.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_kernel_script_source() {

  # prinf "Initialise main function of kernel script source\n";

  install_kernel "$@"

}

main_kernel_script_source "$@"
