#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: kompare-merge-pack
## @Creation date file: 12.11.2020, 22:58:28

[[ -z "${kompare_merge_pack_script_source}" ]] && declare -rx kompare_merge_pack_script_source="$BASH_SOURCE"

if [[ -z "${kompare_merge_pack_script_source_path}" ]]; then
  temp_one="$(dirname ${kompare_merge_pack_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx kompare_merge_pack_script_source_path="$(pwd)"
  else
    declare -rx kompare_merge_pack_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_kompare_merge_pack() {

  local install_pkg=(
    # Краткое опис : A utility which provides statistics based on the output of diff
    # URL          : http://invisible-island.net/diffstat
    # Лицензия     : MIT
    # Описание     : The diff command compares files line by line.  Diffstat reads the
    # : output of the diff command and displays a histogram of the insertions,
    # : deletions and modifications in each file.  Diffstat is commonly used
    # : to provide a summary of the changes in large, complex patch files.
    # :
    # : Install diffstat if you need a program which provides a summary of the
    # : diff command's output.
    'diffutils'
    #
    # Краткое опис : XML diff and merge
    # URL          : http://www.mangrove.cz/diffmark/
    # Лицензия     : diffmark and (GPL+ or Artistic)
    # Описание     : This is an XML diff and merge package. It consists of a shared library and
    # : two utilities: dm and dm-merge.
    'diffmark'
    # 'diffmark-devel'
    #
    # Краткое опис : In-depth comparison of files, archives, and directories
    # URL          : https://diffoscope.org/
    # Лицензия     : GPLv3+
    # Описание     : diffoscope will try to get to the bottom of what makes files or directories
    # : different. It will recursively unpack archives of many kinds and transform
    # : various binary formats into more human readable form to compare them. It can
    # : compare two tarballs, ISO images, or PDF just as easily. The differences can
    # : be shown in a text or HTML report.
    # :
    # : diffoscope is developed as part of the "reproducible builds" Debian project and
    # : was formerly known as "debbindiff".
    # 'diffoscope'
    #
    # Краткое опис : PDF files comparator
    # URL          : http://www.qtrac.eu/diffpdf.html
    #Лицензия     : GPLv2+
    # Описание     : DiffPDF is used to compare two PDF files. By default the comparison is
    # : of the text on each pair of pages, but comparing the appearance of pages
    # : is also supported (for example, if a diagram is changed or a paragraph
    # : reformatted). It is also possible to compare particular pages or page
    # : ranges.
    'diffpdf'
    #
    # Краткое опис : A simple tool for visually comparing two PDF files
    # URL          : http://vslavik.github.io/diff-pdf/
    # Лицензия     : GPLv2+ and LGPLv2+
    # Описание     : A simple tool for visually comparing two PDF files.
    'diff-pdf'
    # Краткое опис : A utility which provides statistics based on the output of diff
    # URL          : http://invisible-island.net/diffstat
    # Лицензия     : MIT
    # Описание     : The diff command compares files line by line.  Diffstat reads the
    # : output of the diff command and displays a histogram of the insertions,
    # : deletions and modifications in each file.  Diffstat is commonly used
    # : to provide a summary of the changes in large, complex patch files.
    # :
    # : Install diffstat if you need a program which provides a summary of the
    # : diff command's output.
    'diffstat'
    #
    # Краткое опис : Compare + merge 2 or 3 files or directories
    # URL          : https://github.com/KDE/kdiff3
    # Лицензия     : GPLv2
    # Описание     : KDiff3 is a program that
    # : - compares and merges two or three input files or directories,
    # : - shows the differences line by line and character by character (!),
    # : - provides an automatic merge-facility and
    # : - an integrated editor for comfortable solving of merge-conflicts
    # : - has support for KDE-KIO (ftp, sftp, http, fish, smb)
    # : - and has an intuitive graphical user interface.
    'kdiff3'
    #
    # Краткое опис : Diff tool
    # URL          : https://cgit.kde.org/kompare.git
    # Лицензия     : GPLv2+ and GFDL
    # Описание     : Tool to visualize changes between two versions of a file
    'kompare'
    'kompare-libs'
    # 'kompare-devel'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/kompare-merge-pack.txt"
  pm "$@" -- "${install_pkg[@]}"

}

function main_kompare_merge_pack_script_source() {

  # printf "Initialise main function of kompare-merge-pack script source\n";

  install_kompare_merge_pack "$@"

}

main_kompare_merge_pack_script_source "$@"
