#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: linux-perf-gui
## @Creation date file: 20.10.2020, 15:43:18

[[ -z "${linux_perf_gui_script_source}" ]] && declare -rx linux_perf_gui_script_source="$BASH_SOURCE"

if [[ -z "${linux_perf_gui_script_source_path}" ]]; then
  temp_one="$(dirname ${linux_perf_gui_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx linux_perf_gui_script_source_path="$(pwd)"
  else
    declare -rx linux_perf_gui_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_linux_perf_gui() {

  echo -e "https://github.com/KDAB/hotspot#on-fedora\n"

  . "${main_project_path}/application/installation/rpm/kernel"
  . "${main_project_path}/application/installation/rpm/qt5"

  local install_pkg=(
    'cmake'
    'gcc'
    'glibc-static'
    'gcc-c++'
    'libstdc++-static'
    'extra-cmake-modules'
    'elfutils-devel'
    'kf5-threadweaver-devel'
    'kf5-ki18n-devel'
    'kf5-kconfigwidgets-devel'
    'kf5-kitemviews-devel'
    'kf5-kitemmodels-devel'
    'kf5-kio-devel'
    'kf5-solid-devel'
    'kf5-kwindowsystem-devel'
    'hotspot'
    'perf'
  )

  pm "$@" -- "${install_pkg[@]}"

}

function main_linux_perf_gui_script_source() {

  # printf "Initialise main function of linux-perf-gui script source\n";

  install_linux_perf_gui "$@"

}

main_linux_perf_gui_script_source "$@"
