#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: tools-monitoring-computer-and-system
## @Creation date file: 01.10.2020, 05:01:30

[[ -z "${tools_monitoring_computer_and_system_script_source}" ]] && declare -rx tools_monitoring_computer_and_system_script_source="$BASH_SOURCE"

if [[ -z "${tools_monitoring_computer_and_system_script_source_path}" ]]; then
  temp_one="$(dirname ${tools_monitoring_computer_and_system_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx tools_monitoring_computer_and_system_script_source_path="$(pwd)"
  else
    declare -rx tools_monitoring_computer_and_system_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_tools_monitoring_computer_and_system() {

  local install_pkg=(
    'lm_sensors'
    'nmon'
    'collectd'
    'glances'
    # 'cpu-x'
    'screenfetch'
    'neofetch'
    'hardinfo'
    # 'gst'
    'htop'
    # 'saidar'
    # 'i-nex'
    'grub-customizer'
  )

  [[ -z "$(lspci | grep NVIDIA)" ]] || install_pkg+=('gwe')

  pm "$@" -- "${install_pkg[@]}"

}

function main_tools_monitoring_computer_and_system_script_source() {

  # prinf "Initialise main function of tools-monitoring-computer-and-system script source\n";

  install_tools_monitoring_computer_and_system "$@"

}

main_tools_monitoring_computer_and_system_script_source "$@"
