#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: video-packs
## @Creation date file: 11.11.2020, 22:49:51

[[ -z "${video_packs_script_source}" ]] && declare -rx video_packs_script_source="$BASH_SOURCE"

if [[ -z "${video_packs_script_source_path}" ]]; then
  temp_one="$(dirname ${video_packs_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx video_packs_script_source_path="$(pwd)"
  else
    declare -rx video_packs_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_video_packs() {

  local install_pkg=(
    # Краткое опис : Digital VCR and streaming server
    # URL : http://ffmpeg.org/
    # Описание : FFmpeg is a complete and free Internet live audio and video
    # : broadcasting solution for Linux/Unix. It also includes a digital
    # : VCR. It can encode in real time in many formats including MPEG1 audio
    # : and video, MPEG4, h263, ac3, asf, avi, real, mjpeg, and flash.
    'ffmpeg'
    'ffmpeg-libs'
    'ffmpeg-devel'
    #
    # Краткое опис : Lightweight video thumbnailer that can be used by file managers
    # URL : https://github.com/dirkvdb/ffmpegthumbnailer
    # Описание : This video thumbnailer can be used to create thumbnails for your video files.
    # -> 'ffmpegthumbnailer'
    # -> 'ffmpegthumbnailer-devel'
    #
    # Краткое опис : KDE ffmpegthumbnailer service
    # URL : https://projects.kde.org/projects/kde/kdemultimedia/ffmpegthumbs
    # Описание : KDE ffmpegthumbnailer service
    # -> 'ffmpegthumbs'
  )

  pm "$@" -- "${install_pkg[@]}"

}

function main_video_packs_script_source() {

  # printf "Initialise main function of video-packs script source\n";

  install_video_packs "$@"

}

main_video_packs_script_source "$@"
