#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: vscode
## @Creation date file: 23.10.2020, 18:47:50

[[ -z "${vscode_script_source}" ]] && declare -rx vscode_script_source="$BASH_SOURCE"

if [[ -z "${vscode_script_source_path}" ]]; then
  temp_one="$(dirname ${vscode_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx vscode_script_source_path="$(pwd)"
  else
    declare -rx vscode_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_fonts_ligature() {

  sudo dnf copr enable "evana/fira-code-fonts" -y
  pm -a -- "fira-code-fonts"

  fc-cache -f -v

  echo "Please configure VSCode: { \"editor.fontFamily\": \"'Fira Code Retina' or 'Fira code'\", \
\"editor.fontLigatures\": true" }

}

function install_vscode() {

  . "${main_project_path}/application/installation/rpm/gvfs"
  . "${main_project_path}/repository/vscode"

  local install_pkg=(
    'code'
    'nodejs'
    'npm'
    'fira-code-fonts'
    'php'
  )

  printf '%s\n' $(unset_dupes_in_array "${install_pkg[@]}") | sort -o "${main_project_path}/package-list/vscode.txt"
  pm "$@" -- "${install_pkg[@]}"

  fc-cache -f -v

  echo 'Please configure VSCode: "editor.fontFamily": "Fira Code Retina or Fira code" and "editor.fontLigatures": true'

  # install_fonts_ligature

}

function main_vscode_script_source() {

  # printf "Initialise main function of vscode script source\n";

  install_vscode "$@"

}

main_vscode_script_source "$@"
