#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: corectrl
## @Creation date file: 17.12.2020, 09:29:51

[[ -z "${corectrl_script_source}" ]] && declare -rx corectrl_script_source="$BASH_SOURCE"

if [[ -z "${corectrl_script_source_path}" ]]; then
  temp_one="$(dirname ${corectrl_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx corectrl_script_source_path="$(pwd)"
  else
    declare -rx corectrl_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_corectrl() {

  . "${main_project_path}/application/installation/rpm/CPU"

  if [[ -f "/usr/share/applications/org.corectrl.corectrl.desktop" ]]; then
    echo -e "\nExecute this command on a terminal\n"
    cp "/usr/share/applications/org.corectrl.corectrl.desktop" "/home/${session_user}/.config/autostart/org.corectrl.corectrl.desktop"
  fi

  echo -en "\n  CoreCtrl uses a helper with root privileges to control your system.
  In order to start the helper, the system will ask you to enter your user password.
  If you want to avoid being asked every time for your password, you can grant root access to the helper permanently. (N/y)"

  read temp_one
  if [[ "${temp_one}" == 'Y' || "${temp_one}" == 'y' ]]; then
    cat <<EOF | sudo tee '/etc/polkit-1/rules.d/90-corectrl.rules' >/dev/null
polkit.addRule(function(action, subject) {
  if ((action.id == "org.corectrl.helper.init" ||
    action.id == "org.corectrl.helperkiller.init") &&
    subject.local == true &&
    subject.active == true &&
    subject.isInGroup("${session_group}")) {
      return polkit.Result.YES;
    }
});
EOF
  fi

}

function main_corectrl_script_source() {

  # printf "Initialise main function of corectrl script source\n";

  install_corectrl "$@"

}

main_corectrl_script_source "$@"
