#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: monitoring-computer-parameter
## @Creation date file: 01.10.2020, 05:01:30

[[ -z "${monitoring_computer_parameter_script_source}" ]] && declare -rx monitoring_computer_parameter_script_source="$BASH_SOURCE"

if [[ -z "${monitoring_computer_parameter_script_source_path}" ]]; then
  temp_one="$(dirname ${monitoring_computer_parameter_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx monitoring_computer_parameter_script_source_path="$(pwd)"
  else
    declare -rx monitoring_computer_parameter_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function main_monitoring_computer_parameter_script_source() {

  # prinf "Initialise main function of monitoring-computer-parameter script source\n";

  if [[ -z "$(check_installed_packages lm_sensors hddtemp nmon collectd)" ]]; then
    . "${main_project_path}/application/installation/rpm/tools-monitoring-computer-and-system"
  else
    printf "Check lm_sensors, hddtemp, nmon, collectd is OK\n"
  fi

  if [[ "$(systemctl is-active lm_sensors)" != "active" ]]; then
    echo "Initialise and start lms_sensors ? (Y/n)"
    read key
    if [[ ${key} == 'y' ]]; then
      sudo systemctl enable lm_sensors
      sensors-detect
      sudo systemctl start lm_sensors
    fi
  fi

  if [[ "$(systemctl is-active hddtemp)" != "active" ]]; then
    echo "Initialise and start hddtemp ? (Y/n)"
    read key
    if [[ ${key} == 'y' ]]; then
      sudo systemctl enable hddtemp
      sensors-detect
      sudo systemctl start hddtemp
      echo "Please visit http://127.0.0.1:7634"
    fi
  fi

  echo "Please run sensors for more information"
  echo "Please visit http://127.0.0.1:7634 for use hddtemp"

}

main_monitoring_computer_parameter_script_source "$@"
