#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: vscode
## @Creation date file: 23.10.2020, 18:27:20

[[ -z "${vscode_script_source}" ]] && declare -rx vscode_script_source="$BASH_SOURCE"

if [[ -z "${vscode_script_source_path}" ]]; then
  temp_one="$(dirname ${vscode_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx vscode_script_source_path="$(pwd)"
  else
    declare -rx vscode_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function preparation_vscode() {

  . "${main_project_path}/application/installation/rpm/vscode"

  if [[ "$(cat /proc/sys/fs/inotify/max_user_watches)" != '524288' ]]; then
    if ! grep -q 'fs.inotify.max_user_watches' '/etc/sysctl.conf'; then
      echo 'fs.inotify.max_user_watches = 524288' | sudo tee -a '/etc/sysctl.conf' >/dev/null
    else
      sudo sed -i 's/fs.inotify.max_user_watches.*$/fs.inotify.max_user_watches = 524288/' '/etc/sysctl.conf'
    fi
    sudo sysctl -p
  fi

}

function main_vscode_script_source() {

  # printf "Initialise main function of vscode script source\n";

  preparation_vscode "$@"

}

main_vscode_script_source "$@"
